import type { NextPage } from "next";
import Head from "next/head";
import { Post } from "../../typings";
import { sanityClient, urlFor } from "../../sanity";

interface Props {
	posts: [Post];
}

export default function SinglePost({ posts }: Props) {
	return (
		<div>
			<Head>
				<title>345pi - news</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				{posts.map((post: Post) => (
					<p key={post._id}>{post.title}</p>
				))}
			</main>
		</div>
	);
}

export const getServerSideProps = async () => {
	const query = `*[_type == "post"]`;
	const posts = await sanityClient.fetch(query);
	return {
		props: {
			posts,
		},
	};
};
